apiVersion: v2
name: kube-ec-gateway
description: A Helm chart for kube-ec API Gateway service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kube-ec
  - gateway
  - api
  - microservices
maintainers:
  - name: kube-ec-team
