# このファイルは例です。実際の値は base64 エンコードが必要です
# echo -n "your-value" | base64

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  database-url: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQGhvc3Q6NTQzMi9kYm5hbWU=  # 例: postgres://user:password@host:5432/dbname
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: eW91ci1zZWNyZXQta2V5LWhlcmU=  # 例: your-secret-key-here
