apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-ec-user.fullname" . }}
  labels:
    {{- include "kube-ec-user.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    {{- include "kube-ec-user.selectorLabels" . | nindent 4 }}
