apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-ec-gateway.fullname" . }}
  labels:
    {{- include "kube-ec-gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kube-ec-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-ec-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-ec-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: PORT
          value: {{ .Values.env.port | quote }}
        - name: GIN_MODE
          value: {{ .Values.env.ginMode | quote }}
        - name: AUTH_SERVICE_ADDR
          value: {{ .Values.env.authServiceAddr | quote }}
        - name: USER_SERVICE_ADDR
          value: {{ .Values.env.userServiceAddr | quote }}
        - name: PRODUCT_SERVICE_ADDR
          value: {{ .Values.env.productServiceAddr | quote }}
        - name: ORDER_SERVICE_ADDR
          value: {{ .Values.env.orderServiceAddr | quote }}
        - name: PAYMENT_SERVICE_ADDR
          value: {{ .Values.env.paymentServiceAddr | quote }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
